%% cylinder_bounded_roms.m
% Polynomial Optimization Methods for Dynamical Systems
% Auxiliary Functions, Sum-of-Squares Programming, and Applications
%
% Chapter: Data-Driven Auxiliary Function Methods
% Example: Structure-preserving ROM learning for cylinder wake data
%
% Loads POD coefficients generated by cylinder_generate_pod_data.m and
% compares:
%
%   1. unconstrained quadratic least-squares ROMs,
%   2. bounded, energy-preserving quadratic ROMs.
%
% Input:
%   cylinder_Re100_POD10_projected_all.mat
%
% Output:
%   cylinder_bounded_rom_results.mat
%   cylinder_rom_timeseries.pdf
%   cylinder_rom_plane.pdf
%
% Requirements:
%   - MATLAB
%   - YALMIP
%   - MOSEK
%
% -------------------------------------------------------------------------

clear; clc; close all;
yalmip('clear');

%% User settings

dataFile = 'cylinder_Re100_POD10_projected_all.mat';

modeList = [4 6 8 10];

trainTimeStart = 1;
forecastTime = 200;

maxAltIters = 8;
alpha0 = 0;
tolAlt = 1e-4;

useWeights = true;
bBox = 100;

plotModeForBook = 4;

saveFigures = true;
saveData = true;

solverOpts = sdpsettings( ...
    'solver','mosek', ...
    'verbose',0, ...
    'debug',0);

%% Book plotting style

S.blue  = [0, 92, 175]/255;
S.red   = [200, 50, 50]/255;
S.black = [0, 0, 0];

%% Load POD time series

load(dataFile,'A','snapTimes');

tau = mean(diff(snapTimes));

fprintf('\n============================================================\n');
fprintf('Cylinder wake bounded ROM learning\n');
fprintf('============================================================\n\n');

fprintf('Loaded %d snapshots, %d POD coordinates, tau = %.6g\n', ...
    size(A,1),size(A,2),tau);

modeList = modeList(modeList <= size(A,2));

results = struct();

%% Main loop over ROM dimensions

for rr = 1:numel(modeList)

    n = modeList(rr);

    fprintf('\n============================================================\n');
    fprintf('Learning ROM with %d POD modes\n',n);
    fprintf('============================================================\n');

    Araw = A(:,1:n);
    t = snapTimes(:);

    pairTimes = t(1:end-1);
    trainIdx = pairTimes >= trainTimeStart;

    if nnz(trainIdx) < 20
        error('Too few training pairs. Decrease trainTimeStart.');
    end

    %% Center and scale using training states

    AtrainStates = Araw(trainIdx,:);

    mu = mean(AtrainStates,1);
    sig = std(AtrainStates,0,1);
    sig(sig < 1e-12) = 1;

    Zraw = (Araw - mu)./sig;

    %% Snapshot pairs

    Xall = Zraw(1:end-1,:);
    Yall = Zraw(2:end,:);
    dXall = (Yall - Xall)/tau;

    X = Xall(trainIdx,:);
    dX = dXall(trainIdx,:);

    Ntrain = size(X,1);

    %% Endpoint-flat weights

    if useWeights
        s = (1:Ntrain)'/(Ntrain+1);
        w = exp(-1./(s.*(1-s)));
        w = w/sum(w);
    else
        w = ones(Ntrain,1)/Ntrain;
    end

    Wsqrt = spdiags(sqrt(w),0,Ntrain,Ntrain);

    %% Quadratic library

    Phi = quadratic_library(X);

    %% Unconstrained weighted least squares

    PhiW = Wsqrt*Phi;
    dXW  = Wsqrt*dX;

    XiLS = PhiW\dXW;
    modelLS = unpack_quadratic_model(XiLS,n);

    oneStepLS = norm(Phi*XiLS - dX,'fro')/norm(dX,'fro');

    oneStepLSWeighted = ...
        norm(Wsqrt*(Phi*XiLS - dX),'fro')/norm(Wsqrt*dX,'fro');

    energyResidualLS = energy_preservation_residual(modelLS);

    fprintf('Unconstrained LS unweighted one-step error = %.4e\n',oneStepLS);
    fprintf('Unconstrained LS weighted one-step error   = %.4e\n',oneStepLSWeighted);
    fprintf('Unconstrained LS energy residual           = %.4e\n',energyResidualLS);

    %% Alternating bounded model discovery

    b = zeros(n,1);
    alpha = alpha0;

    prevLoss = inf;
    modelB = [];

    for iter = 1:maxAltIters

        fprintf('\nAlt iter %d: alpha = %.3e\n',iter,alpha);

        [modelTry,lossB,feasible] = solve_bounded_regression_fast( ...
            Phi,dX,Wsqrt,b,alpha,n,solverOpts);

        if ~feasible

            warning('Regression infeasible at alpha = %.3e. Reducing alpha.',alpha);

            alpha = alpha/10;

            if alpha < 1e-12
                alpha = 0;
                warning('Retrying with alpha = 0.');
            end

            [modelTry,lossB,feasible] = solve_bounded_regression_fast( ...
                Phi,dX,Wsqrt,b,alpha,n,solverOpts);

            if ~feasible
                warning('Still infeasible. Stopping bounded fit for n = %d.',n);
                break;
            end
        end

        modelB = modelTry;

        [bNew,alphaNew,feasibleB] = solve_background_sdp(modelB,bBox,solverOpts);

        if ~feasibleB
            warning('Background optimization infeasible. Keeping previous b, alpha.');
            bNew = b;
            alphaNew = alpha;
        end

        fprintf('  squared weighted loss = %.4e, alpha_new = %.4e, |db| = %.4e\n', ...
            lossB,alphaNew,norm(bNew-b));

        if isfinite(prevLoss) && ...
                abs(prevLoss-lossB)/(1+abs(prevLoss)) < tolAlt && ...
                norm(bNew-b)/(1+norm(b)) < tolAlt && ...
                abs(alphaNew-alpha)/(1+abs(alpha)) < tolAlt

            b = bNew;
            alpha = alphaNew;

            fprintf('  Converged.\n');
            break;
        end

        b = bNew;
        alpha = alphaNew;
        prevLoss = lossB;
    end

    if isempty(modelB)
        warning('No feasible bounded model found for n = %d. Skipping.',n);
        continue;
    end

    %% Final bounded regression

    [modelFinal,lossFinal,feasibleFinal] = solve_bounded_regression_fast( ...
        Phi,dX,Wsqrt,b,alpha,n,solverOpts);

    if feasibleFinal
        modelB = modelFinal;
        fprintf('Final bounded regression succeeded. Squared weighted loss = %.4e\n',lossFinal);
    else
        warning('Final bounded regression infeasible. Keeping previous bounded model.');
        lossFinal = prevLoss;
    end

    [bFinal,alphaFinal,feasibleFinalB] = solve_background_sdp(modelB,bBox,solverOpts);

    if feasibleFinalB
        b = bFinal;
        alpha = alphaFinal;
    else
        warning('Final background SDP infeasible. Keeping previous b, alpha.');
    end

    modelB.b = b;
    modelB.alpha = alpha;

    XiB = pack_quadratic_model(modelB);

    oneStepB = norm(Phi*XiB - dX,'fro')/norm(dX,'fro');

    oneStepBWeighted = ...
        norm(Wsqrt*(Phi*XiB - dX),'fro')/norm(Wsqrt*dX,'fro');

    energyResidualB = energy_preservation_residual(modelB);

    fprintf('Bounded unweighted one-step error = %.4e\n',oneStepB);
    fprintf('Bounded weighted one-step error   = %.4e\n',oneStepBWeighted);
    fprintf('Bounded energy residual           = %.4e\n',energyResidualB);
    fprintf('Bounded alpha                     = %.4e\n',alpha);

    %% Rollouts

    tDataFull = t - t(1);
    tEndForecast = tDataFull(end) + forecastTime;
    tspanFull = (0:tau:tEndForecast).';

    z0Full = Zraw(1,:).';

    idxTrainStart = find(pairTimes >= trainTimeStart,1,'first');

    tDataTrain = t(idxTrainStart:end) - t(idxTrainStart);
    tspanTrain = (0:tau:(tDataTrain(end) + forecastTime)).';

    z0Train = Zraw(idxTrainStart,:).';
    AdataTrain = Araw(idxTrainStart:end,:);

    fprintf('train start index = %d, t = %.16f\n',idxTrainStart,t(idxTrainStart));
    fprintf('first model IC raw a1 = %.8e\n',unscale_data(z0Train.',mu,sig));
    fprintf('first data raw a1     = %.8e\n',AdataTrain(1,1));

    odeOpts = odeset( ...
        'RelTol',1e-7, ...
        'AbsTol',1e-9, ...
        'MaxStep',5*tau);

    [tLSFull,ZlsFull] = safe_rollout(@(tt,z) quadratic_rhs(tt,z,modelLS), ...
        tspanFull,z0Full,odeOpts);

    [tBFull,ZbFull] = safe_rollout(@(tt,z) quadratic_rhs(tt,z,modelB), ...
        tspanFull,z0Full,odeOpts);

    [tLSTrain,ZlsTrain] = safe_rollout(@(tt,z) quadratic_rhs(tt,z,modelLS), ...
        tspanTrain,z0Train,odeOpts);

    [tBTrain,ZbTrain] = safe_rollout(@(tt,z) quadratic_rhs(tt,z,modelB), ...
        tspanTrain,z0Train,odeOpts);

    fprintf('  LS full rollout reached %.3f / %.3f\n',tLSFull(end),tspanFull(end));
    fprintf('  bounded full rollout reached %.3f / %.3f\n',tBFull(end),tspanFull(end));
    fprintf('  LS train rollout reached %.3f / %.3f\n',tLSTrain(end),tspanTrain(end));
    fprintf('  bounded train rollout reached %.3f / %.3f\n',tBTrain(end),tspanTrain(end));

    AlsFull = unscale_data(ZlsFull,mu,sig);
    AbFull  = unscale_data(ZbFull,mu,sig);

    AlsTrain = unscale_data(ZlsTrain,mu,sig);
    AbTrain  = unscale_data(ZbTrain,mu,sig);

    AdataFull = Araw;

    %% Error metrics

    nFullLS = min(size(AdataFull,1),size(AlsFull,1));
    nFullB  = min(size(AdataFull,1),size(AbFull,1));

    nTrainLS = min(size(AdataTrain,1),size(AlsTrain,1));
    nTrainB  = min(size(AdataTrain,1),size(AbTrain,1));

    rolloutLSFull = normalized_rollout_error( ...
        AlsFull(1:nFullLS,:),AdataFull(1:nFullLS,:));

    rolloutBFull = normalized_rollout_error( ...
        AbFull(1:nFullB,:),AdataFull(1:nFullB,:));

    rolloutLSTrain = normalized_rollout_error( ...
        AlsTrain(1:nTrainLS,:),AdataTrain(1:nTrainLS,:));

    rolloutBTrain = normalized_rollout_error( ...
        AbTrain(1:nTrainB,:),AdataTrain(1:nTrainB,:));

    fprintf('\nMode count %d results:\n',n);
    fprintf('  LS unweighted one-step error       = %.4e\n',oneStepLS);
    fprintf('  bounded unweighted one-step error  = %.4e\n',oneStepB);
    fprintf('  LS weighted one-step error         = %.4e\n',oneStepLSWeighted);
    fprintf('  bounded weighted one-step error    = %.4e\n',oneStepBWeighted);
    fprintf('  LS rollout error, full IC          = %.4e\n',rolloutLSFull);
    fprintf('  bounded rollout error, full IC     = %.4e\n',rolloutBFull);
    fprintf('  LS rollout error, train IC         = %.4e\n',rolloutLSTrain);
    fprintf('  bounded rollout error, train IC    = %.4e\n',rolloutBTrain);
    fprintf('  bounded alpha                      = %.4e\n',alpha);
    fprintf('  LS energy-preservation residual    = %.4e\n',energyResidualLS);
    fprintf('  bounded energy-pres. residual      = %.4e\n',energyResidualB);

    %% Far-field boundedness test

    nFarIC = 20;
    farRadius = 25;
    tFarEnd = 1000;
    tspanFar = (0:tau:tFarEnd).';

    rng(10+n);

    farStatsLS = zeros(nFarIC,4);
    farStatsB  = zeros(nFarIC,4);

    for j = 1:nFarIC

        z0 = randn(n,1);
        z0 = farRadius*z0/norm(z0);

        [tLSFar,ZlsFar] = safe_rollout(@(tt,z) quadratic_rhs(tt,z,modelLS), ...
            tspanFar,z0,odeOpts);

        [tBFar,ZbFar] = safe_rollout(@(tt,z) quadratic_rhs(tt,z,modelB), ...
            tspanFar,z0,odeOpts);

        rLS = vecnorm(ZlsFar,2,2);
        rB  = vecnorm(ZbFar,2,2);

        reachedLS = abs(tLSFar(end)-tspanFar(end)) <= 10*eps(max(1,tspanFar(end)));
        reachedB  = abs(tBFar(end)-tspanFar(end))  <= 10*eps(max(1,tspanFar(end)));

        failedLS = ~reachedLS || any(~isfinite(rLS));
        failedB  = ~reachedB  || any(~isfinite(rB));

        farStatsLS(j,:) = [max(rLS), rLS(end), reachedLS, failedLS];
        farStatsB(j,:)  = [max(rB),  rB(end),  reachedB,  failedB];
    end

    fprintf('\nFar-field boundedness test, n = %d:\n',n);
    fprintf('  LS:      median max radius = %.4e, median final radius = %.4e, failures = %d/%d\n', ...
        median(farStatsLS(:,1),'omitnan'), ...
        median(farStatsLS(:,2),'omitnan'), ...
        nnz(farStatsLS(:,4)), nFarIC);

    fprintf('  bounded: median max radius = %.4e, median final radius = %.4e, failures = %d/%d\n', ...
        median(farStatsB(:,1),'omitnan'), ...
        median(farStatsB(:,2),'omitnan'), ...
        nnz(farStatsB(:,4)), nFarIC);

    %% Store results

    results(rr).n = n;

    results(rr).modelLS = modelLS;
    results(rr).modelB = modelB;

    results(rr).mu = mu;
    results(rr).sig = sig;

    results(rr).trainTimeStart = trainTimeStart;
    results(rr).forecastTime = forecastTime;

    results(rr).oneStepLS = oneStepLS;
    results(rr).oneStepB = oneStepB;
    results(rr).oneStepLSWeighted = oneStepLSWeighted;
    results(rr).oneStepBWeighted = oneStepBWeighted;

    results(rr).energyResidualLS = energyResidualLS;
    results(rr).energyResidualB = energyResidualB;

    results(rr).rolloutLSFull = rolloutLSFull;
    results(rr).rolloutBFull = rolloutBFull;
    results(rr).rolloutLSTrain = rolloutLSTrain;
    results(rr).rolloutBTrain = rolloutBTrain;

    results(rr).AdataFull = AdataFull;
    results(rr).AlsFull = AlsFull;
    results(rr).AbFull = AbFull;

    results(rr).AdataTrain = AdataTrain;
    results(rr).AlsTrain = AlsTrain;
    results(rr).AbTrain = AbTrain;

    results(rr).tLSFull = tLSFull;
    results(rr).tBFull = tBFull;
    results(rr).tLSTrain = tLSTrain;
    results(rr).tBTrain = tBTrain;

    results(rr).tDataFull = tDataFull;
    results(rr).tDataTrain = tDataTrain;

    results(rr).farRadius = farRadius;
    results(rr).tFarEnd = tFarEnd;
    results(rr).farStatsLS = farStatsLS;
    results(rr).farStatsB = farStatsB;

    results(rr).b = b;
    results(rr).alpha = alpha;
    results(rr).lossFinalSquaredWeighted = lossFinal;
end

%% Save results

if saveData
    save('cylinder_bounded_rom_results.mat', ...
        'results','modeList','trainTimeStart','forecastTime','useWeights');

    fprintf('\nSaved results: cylinder_bounded_rom_results.mat\n');
end

%% Book plots

plotIdx = find([results.n] == plotModeForBook,1);

if isempty(plotIdx)
    plotIdx = find(arrayfun(@(s)isfield(s,'n') && ~isempty(s.n),results),1,'first');
end

if isempty(plotIdx)
    warning('No successful ROM available for plotting.');
else

    Rplot = results(plotIdx);

    fig1 = figure;
    set(fig1,'Color','w','Units','centimeters','Position',[2 2 12 8]);

    plot(Rplot.tDataTrain,Rplot.AdataTrain(:,1),'k--','LineWidth',1);
    hold on
    plot(Rplot.tLSTrain,Rplot.AlsTrain(:,1),'Color',S.red,'LineWidth',3);
    plot(Rplot.tBTrain,Rplot.AbTrain(:,1),'Color',S.blue,'LineWidth',3);

    xlabel('$t$','Interpreter','latex','FontSize',24);
    ylabel('$a_1$','Interpreter','latex','FontSize',24);

    legend('data','LS','bounded','Location','best');

    xlim([0 150]);
    ylim([-120 120]);

    box on
    grid on

    set(gca,'FontSize',18,'TickLabelInterpreter','latex');

    if saveFigures
        export_pdf(fig1,'cylinder_rom_timeseries.pdf');
    end

    fig2 = figure;
    set(fig2,'Color','w','Units','centimeters','Position',[2 2 9 9]);

    plot(Rplot.AdataTrain(:,1),Rplot.AdataTrain(:,2),'k--','LineWidth',1);
    hold on
    plot(Rplot.AlsTrain(:,1),Rplot.AlsTrain(:,2),'Color',S.red,'LineWidth',3);
    plot(Rplot.AbTrain(:,1),Rplot.AbTrain(:,2),'Color',S.blue,'LineWidth',3);

    xlabel('$a_1$','Interpreter','latex','FontSize',24);
    ylabel('$a_2$','Interpreter','latex','FontSize',24);

    legend('data','LS','bounded','Location','best');

    xlim([-120 120]);
    ylim([-120 120]);

    box on
    grid on
    axis square

    set(gca,'FontSize',18,'TickLabelInterpreter','latex');

    if saveFigures
        export_pdf(fig2,'cylinder_rom_plane.pdf');
    end
end

fprintf('\nFinished cylinder bounded-ROM example.\n');

%% Local functions

function Phi = quadratic_library(X)

    [N,n] = size(X);
    nq = n*(n+1)/2;

    Phi = zeros(N,1+n+nq);
    Phi(:,1) = 1;
    Phi(:,2:1+n) = X;

    col = 1+n;

    for i = 1:n
        for j = i:n
            col = col + 1;
            Phi(:,col) = X(:,i).*X(:,j);
        end
    end
end

function [model,lossVal,feasible] = solve_bounded_regression_fast( ...
    Phi,dX,Wsqrt,b,alpha,n,opts)

    nFeatures = size(Phi,2);

    Xi = sdpvar(nFeatures,n,'full');

    R = Wsqrt*(dX - Phi*Xi);
    objective = R(:)'*R(:);

    constraints = [];

    constraints = [constraints, energy_preservation_constraints_xi(Xi,n)];

    Ab = shifted_linear_operator_xi(Xi,n,b);

    constraints = [constraints, 0.5*(Ab+Ab') <= -alpha*eye(n)];

    diagnostics = optimize(constraints,objective,opts);

    feasible = diagnostics.problem == 0;

    if feasible
        XiVal = value(Xi);
        lossVal = value(objective);
        model = unpack_quadratic_model(XiVal,n);
    else
        lossVal = inf;
        model = [];
    end
end

function constraints = energy_preservation_constraints_xi(Xi,n)

    constraints = [];

    for a = 1:n
        for b = a:n
            for c = b:n

                inds = unique(perms([a b c]),'rows');
                expr = 0;

                for p = 1:size(inds,1)

                    i = inds(p,1);
                    j = inds(p,2);
                    k = inds(p,3);

                    expr = expr + q_entry_xi(Xi,n,i,j,k);
                end

                constraints = [constraints, expr == 0]; %#ok<AGROW>
            end
        end
    end
end

function qijk = q_entry_xi(Xi,n,i,j,k)

    if j <= k
        row = quad_feature_row(n,j,k);
    else
        row = quad_feature_row(n,k,j);
    end

    if j == k
        qijk = Xi(row,i);
    else
        qijk = 0.5*Xi(row,i);
    end
end

function row = quad_feature_row(n,j,k)

    if j > k
        tmp = j;
        j = k;
        k = tmp;
    end

    row = 1+n;

    for a = 1:n
        for b = a:n

            row = row + 1;

            if a == j && b == k
                return;
            end
        end
    end

    error('Invalid quadratic index.');
end

function Ab = shifted_linear_operator_xi(Xi,n,b)

    L = Xi(2:1+n,:).';
    Ab = L;

    for i = 1:n
        for ell = 1:n

            expr = L(i,ell);

            for j = 1:n
                expr = expr + q_entry_xi(Xi,n,i,j,ell)*b(j);
                expr = expr + q_entry_xi(Xi,n,i,ell,j)*b(j);
            end

            Ab(i,ell) = expr;
        end
    end
end

function model = unpack_quadratic_model(Xi,n)

    model.n = n;
    model.c = Xi(1,:).';
    model.L = Xi(2:1+n,:).';
    model.Q = zeros(n,n,n);

    col = 1+n;

    for j = 1:n
        for k = j:n

            col = col + 1;
            coeff = Xi(col,:).';

            if j == k
                model.Q(:,j,k) = coeff;
            else
                model.Q(:,j,k) = 0.5*coeff;
                model.Q(:,k,j) = 0.5*coeff;
            end
        end
    end
end

function Xi = pack_quadratic_model(model)

    n = model.n;
    nq = n*(n+1)/2;

    Xi = zeros(1+n+nq,n);

    Xi(1,:) = model.c.';
    Xi(2:1+n,:) = model.L.';

    col = 1+n;

    for j = 1:n
        for k = j:n

            col = col + 1;

            if j == k
                Xi(col,:) = squeeze(model.Q(:,j,k)).';
            else
                Xi(col,:) = squeeze(model.Q(:,j,k) + model.Q(:,k,j)).';
            end
        end
    end
end

function [bVal,alphaVal,feasible] = solve_background_sdp(model,bBox,opts)

    n = model.n;

    b = sdpvar(n,1,'full');
    alpha = sdpvar(1,1);

    L = model.L;
    Q = model.Q;

    Ab = sdpvar(n,n,'full');

    for i = 1:n
        for ell = 1:n

            expr = L(i,ell);

            for j = 1:n
                expr = expr + Q(i,j,ell)*b(j);
                expr = expr + Q(i,ell,j)*b(j);
            end

            Ab(i,ell) = expr;
        end
    end

    constraints = [];

    constraints = [constraints, 0.5*(Ab+Ab') <= -alpha*eye(n)];
    constraints = [constraints, alpha >= 0, alpha <= 1e3];
    constraints = [constraints, -bBox <= b <= bBox];

    diagnostics = optimize(constraints,-alpha,opts);

    feasible = diagnostics.problem == 0;

    if feasible
        bVal = value(b);
        alphaVal = value(alpha);
    else
        bVal = zeros(n,1);
        alphaVal = 0;
    end
end

function dx = quadratic_rhs(~,x,model)

    n = model.n;

    dx = model.c + model.L*x;

    for i = 1:n

        val = 0;

        for j = 1:n
            for k = 1:n
                val = val + model.Q(i,j,k)*x(j)*x(k);
            end
        end

        dx(i) = dx(i) + val;
    end
end

function Araw = unscale_data(Z,mu,sig)

    Araw = Z.*sig + mu;
end

function err = normalized_rollout_error(Xmodel,Xdata)

    Xmean = mean(Xdata,1);
    denom = norm(Xdata - Xmean,'fro');

    if denom == 0
        err = norm(Xmodel-Xdata,'fro');
    else
        err = norm(Xmodel-Xdata,'fro')/denom;
    end
end

function res = energy_preservation_residual(model)

    n = model.n;
    Q = model.Q;

    coeffs = [];

    for a = 1:n
        for b = a:n
            for c = b:n

                inds = unique(perms([a b c]),'rows');
                val = 0;

                for p = 1:size(inds,1)

                    i = inds(p,1);
                    j = inds(p,2);
                    k = inds(p,3);

                    val = val + Q(i,j,k);
                end

                coeffs(end+1,1) = val; %#ok<AGROW>
            end
        end
    end

    res = norm(coeffs,2);
end

function [tout,xout] = safe_rollout(rhs,tspan,x0,odeOpts)

    try
        [tout,xout] = ode15s(rhs,tspan,x0,odeOpts);
    catch ME
        warning('ODE integration failed: %s',ME.message);
        tout = tspan(1);
        xout = x0.';
    end

    if isempty(tout) || isempty(xout)
        tout = tspan(1);
        xout = x0.';
    end
end

function export_pdf(fig,fileName)

    set(fig,'PaperUnits','centimeters');
    set(fig,'Units','centimeters');

    pos = get(fig,'Position');

    set(fig,'PaperSize',[pos(3) pos(4)]);
    set(fig,'PaperPositionMode','manual');
    set(fig,'PaperPosition',[0 0 pos(3) pos(4)]);

    print(fig,'-dpdf',fileName);
    fprintf('Saved figure: %s\n',fileName);
end