%% shear_flow_edmd_bounds_plot.m
% Polynomial Optimization Methods for Dynamical Systems
% Auxiliary Functions, Sum-of-Squares Programming, and Applications
%
% Chapter: Data-Driven Auxiliary Function Methods
% Example: Plotting EDMD-SOS shear-flow transition bounds
%
% This script loads previously computed EDMD-SOS bound files generated by
% shear_flow_edmd_bounds.m and reproduces the transition figure from the
% book.
%
% Required MAT-files:
%
%   shear_flow_edmd_bounds_3modes_degV5.mat
%   shear_flow_edmd_bounds_3modes_degV7.mat
%   shear_flow_edmd_bounds_3modes_degV9.mat
%   shear_flow_edmd_bounds_3modes_degV11.mat
%   shear_flow_edmd_bounds_3modes_degV13.mat
%
% Output:
%
%   shear_flow_edmd_transition_bounds.pdf
%
% -------------------------------------------------------------------------

clear; clc; close all;

%% User options

numModes = 3;
degreeList = [5 7 9 11 13];

saveFigure = true;
figureFile = 'shear_flow_edmd_transition_bounds.pdf';

%% Book plotting style

S.blue   = [0, 92, 175]/255;
S.red    = [200, 50, 50]/255;
S.green  = [0, 140, 90]/255;
S.orange = [230, 120, 20]/255;
S.purple = [170, 90, 160]/255;
S.black  = [0, 0, 0];

colors = containers.Map( ...
    {'5','7','9','11','13'}, ...
    {S.blue,S.red,S.green,S.orange,S.purple});

%% Load data

data = struct();

for k = 1:numel(degreeList)

    degV = degreeList(k);

    fileName = sprintf('shear_flow_edmd_bounds_%dmodes_degV%d.mat', ...
        numModes,degV);

    if ~isfile(fileName)
        error('Required file not found: %s',fileName);
    end

    Sload = load(fileName);

    data(k).degV = degV;
    data(k).ReList = Sload.ReList;

    if isfield(Sload,'upperBounds')
        data(k).bounds = Sload.upperBounds;
    elseif isfield(Sload,'bounds')
        data(k).bounds = Sload.bounds;
    else
        error('Could not find upperBounds or bounds in %s.',fileName);
    end
end

%% Optional postprocessing used in the original book figure

for k = 1:numel(data)

    if data(k).degV == 7
        idx5 = find([data.degV] == 5,1);
        if ~isempty(idx5) && isequal(data(k).ReList,data(idx5).ReList)
            data(k).bounds = min(data(k).bounds,data(idx5).bounds);
        end
    end

    if data(k).degV == 13
        idx11 = find([data.degV] == 11,1);
        if ~isempty(idx11)

            Re13 = data(k).ReList;
            Re11 = data(idx11).ReList;
            B11  = data(idx11).bounds;

            B11interp = interp1(Re11,B11,Re13,'linear','extrap');
            data(k).bounds = min(data(k).bounds,B11interp);
        end
    end
end

%% Plot

fig = figure;
set(fig,'Color','w','Units','centimeters','Position',[2 2 13 6]);

hold on
box on
grid on

for k = numel(data):-1:1

    degV = data(k).degV;
    col = colors(num2str(degV));

    plot(data(k).ReList,data(k).bounds,'.-', ...
        'Color',col, ...
        'LineWidth',1.2, ...
        'MarkerSize',25, ...
        'DisplayName',sprintf('$d_V=%d$',degV));
end

ylim([0 1.6]);
xlim([10 100]);

set(gca,'FontSize',18,'TickLabelInterpreter','latex','Layer','top');

xlabel('$Re$','Interpreter','latex','FontSize',24,'FontWeight','bold');
ylabel('Upper bound','Interpreter','latex','FontSize',24,'FontWeight','bold');

legend('Interpreter','latex','FontSize',18,'Location','northwest');

if saveFigure
    save_pdf_figure(fig,figureFile);
end

fprintf('\nFinished shear-flow EDMD bounds plot.\n');

%% Local function

function save_pdf_figure(fig,fileName)

    set(fig,'PaperUnits','centimeters');
    set(fig,'Units','centimeters');

    pos = get(fig,'Position');

    set(fig,'PaperSize',[pos(3) pos(4)]);
    set(fig,'PaperPositionMode','manual');
    set(fig,'PaperPosition',[0 0 pos(3) pos(4)]);

    print(fig,'-dpdf',fileName);
    fprintf('Saved figure: %s\n',fileName);
end